In [4]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

ModuleNotFoundError: No module named 'pandas'

In [80]:
steam = pd.read_csv('C:\\Users\\janek\\Documents\\Steamify\\table_csvs\\steam\\game.csv')
steam.head()

,game_id,game_name,required_age,positive_negative_ratings_ratio,median_playtime,total_ratings,price
0,1,Counter-Strike,0,37.296795,317,127873,7.19
1,2,神明在上(Zengeon),0,5.949153,16,410,6.19
2,7,Rogue Reaper,0,3.085714,0,286,0.00
3,46,某1种青春,0,25.750000,0,107,0.00
4,54,Tiny Snow,0,22.517241,0,682,2.89

In [1]:
scaler = MinMaxScaler(feature_range=(0,100))
numeric_columns = ['positive_negative_ratings_ratio','median_playtime','total_ratings']
scaled_steam = scaler.fit_transform(steam[numeric_columns])
scaled_steam = pd.DataFrame(scaled_steam, columns=numeric_columns, index=steam.index)
scaled_steam.describe()

NameError: name 'MinMaxScaler' is not defined

In [82]:
new_steam=steam.drop(columns=numeric_columns)
new_steam=new_steam.merge(scaled_steam, left_index=True, right_index=True)
new_steam.head()

,game_id,game_name,required_age,price,positive_negative_ratings_ratio,median_playtime,total_ratings
0,1,Counter-Strike,0,7.19,14.271412,0.166295,4.193931
1,2,神明在上(Zengeon),0,6.19,2.231311,0.008393,0.010175
2,7,Rogue Reaper,0,0.00,1.131512,0.000000,0.006105
3,46,某1种青春,0,0.00,9.836482,0.000000,0.000230
4,54,Tiny Snow,0,2.89,8.594834,0.000000,0.019103

In [83]:
new_steam[['game_id','game_name','required_age','positive_negative_ratings_ratio','median_playtime','total_ratings','price']].to_csv('C:\\Users\\janek\\Documents\\Steamify\\table_csvs\\steam\\game.csv',index=False)

In [84]:
spotify = pd.read_csv('C:\\Users\\janek\\Documents\\Steamify\\table_csvs\\spotify\\song.csv')
spotify.head()

,song_id,song_name,album,duration,popularity,explicit,danceability,energy,acousticness,instrumentalness,valence
0,1,iNSaNiTY,Lucid,4.928250,49,False,0.383,0.792,0.06400,0.000000,0.382
1,2,Fighting With The Melody,The Secret Cinematic Sounds of Jimmy Urine,4.128883,58,False,0.734,0.953,0.01630,0.043900,0.741
2,3,Mr. Brightside,Hot Fuss,3.716217,88,False,0.352,0.911,0.00121,0.000000,0.236
3,4,U With Me?,Views,4.956217,65,True,0.429,0.430,0.33800,0.000012,0.125
4,5,Marvins Room,Take Care (Deluxe),5.787100,77,True,0.492,0.260,0.64600,0.001780,0.312

In [85]:
scaler = MinMaxScaler(feature_range=(0,100))
numeric_columns = ['duration','popularity','danceability','energy','acousticness','instrumentalness','valence']
scaled_spotify = scaler.fit_transform(spotify[numeric_columns])
scaled_spotify = pd.DataFrame(scaled_spotify, columns=numeric_columns, index=spotify.index)
scaled_spotify.head()

,duration,popularity,danceability,energy,acousticness,instrumentalness,valence
0,43.780004,53.260870,28.624079,78.769231,6.645437,0.000000,36.996022
1,34.708010,63.043478,71.744472,95.282051,1.692141,4.621053,75.594022
2,30.024665,95.652174,24.815725,90.974359,0.125155,0.000000,21.298785
3,44.097397,70.652174,34.275184,41.641026,35.098329,0.001242,9.364584
4,53.527073,83.695652,42.014742,24.205128,67.081873,0.187368,29.469949

In [86]:
new_spotify=spotify.drop(columns=numeric_columns)
new_spotify=new_spotify.merge(scaled_spotify, left_index=True, right_index=True)
new_spotify.head()

,song_id,song_name,album,explicit,duration,popularity,danceability,energy,acousticness,instrumentalness,valence
0,1,iNSaNiTY,Lucid,False,43.780004,53.260870,28.624079,78.769231,6.645437,0.000000,36.996022
1,2,Fighting With The Melody,The Secret Cinematic Sounds of Jimmy Urine,False,34.708010,63.043478,71.744472,95.282051,1.692141,4.621053,75.594022
2,3,Mr. Brightside,Hot Fuss,False,30.024665,95.652174,24.815725,90.974359,0.125155,0.000000,21.298785
3,4,U With Me?,Views,True,44.097397,70.652174,34.275184,41.641026,35.098329,0.001242,9.364584
4,5,Marvins Room,Take Care (Deluxe),True,53.527073,83.695652,42.014742,24.205128,67.081873,0.187368,29.469949

In [87]:
new_spotify[['song_id','song_name','album','duration','popularity','explicit','danceability','energy','acousticness','instrumentalness','valence']].to_csv('C:\\Users\\janek\\Documents\\Steamify\\table_csvs\\spotify\\song.csv',index=False)